platform :ios, '12.0'

target 'AnonymousMessage' do
  use_frameworks!
  
  # React Native
  pod 'React', :path => '../node_modules/react'
  pod 'React-Core', :path => '../node_modules/react-native'
  pod 'React-RCTActionSheet', :path => '../node_modules/react-native/Libraries/ActionSheetIOS'
  pod 'React-RCTAnimation', :path => '../node_modules/react-native/Libraries/NativeAnimation'
  pod 'React-RCTBlob', :path => '../node_modules/react-native/Libraries/Blob'
  pod 'React-RCTImage', :path => '../node_modules/react-native/Libraries/Image'
  pod 'React-RCTLinking', :path => '../node_modules/react-native/Libraries/LinkingIOS'
  pod 'React-RCTNetwork', :path => '../node_modules/react-native/Libraries/Network'
  pod 'React-RCTSettings', :path => '../node_modules/react-native/Libraries/Settings'
  pod 'React-RCTText', :path => '../node_modules/react-native/Libraries/Text'
  pod 'React-RCTVibration', :path => '../node_modules/react-native/Libraries/Vibration'
  pod 'React-RCTWebSocket', :path => '../node_modules/react-native/Libraries/WebSocket'

  # React Native Community
  pod 'React-NativeModules', :path => '../node_modules/@react-native-community/cli-platform-ios/native_modules'
  pod 'React-CoreModules', :path => '../node_modules/react-native/Libraries/CoreModules'
  pod 'React-DevSupport', :path => '../node_modules/react-native/React/DevSupport'
  pod 'React-RCTFabric', :path => '../node_modules/react-native/React'
  pod 'React-Fabric', :path => '../node_modules/react-native/React'
  pod 'React-Codegen', :path => '../build/generated/ios'
  pod 'RCT-Folly', :podspec => '../node_modules/react-native/third-party-podspecs/RCT-Folly.podspec'
  pod 'DoubleConversion', :podspec => '../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec'
  pod 'glog', :podspec => '../node_modules/react-native/third-party-podspecs/glog.podspec'
  pod 'hermes-engine', podspec: '../node_modules/hermes-engine/hermes-engine.podspec'
  pod 'Yoga', :path => '../node_modules/react-native/ReactCommon/yoga'

  # Tor integration
  pod 'Tor', '~> 0.4.7'
  pod 'TorManager', '~> 0.3.0'
  
  # Additional libraries for security and networking
  pod 'CocoaAsyncSocket', '~> 7.6'
  pod 'OpenSSL-Universal', '~> 1.1.1100'
  
  # Permissions
  pod 'Permission-Location', '~> 3.0'
  
  # Firebase (for push notifications if needed)
  pod 'Firebase/Messaging', '~> 10.0'
  
  # Add other dependencies here
  post_install do |installer|
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '12.0'
        config.build_settings['ENABLE_BITCODE'] = 'NO'
        
        # React Native specific settings
        if target.respond_to?(:product_type) && target.product_type == 'com.apple.product-type.bundle'
          config.build_settings['CODE_SIGNING_ALLOWED'] = 'NO'
        end
      end
    end
  end
end